{% set name = "pyelftools" %}
{% set version = "0.28" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyelftools-{{ version }}.tar.gz
  sha256: 53e5609cac016471d40bd88dc410cd90755942c25e58a61021cfdf7abdfeacff

build:
  number: 1
  # noarch: python
  # this cannot be noarch b/c it has scripts
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - elftools
    - elftools.common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eliben/pyelftools
  summary: Library for analyzing ELF files and DWARF debugging information
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
