{% set version = "0.26" %}

package:
  name: pyelftools
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyelftools/pyelftools-{{ version }}.tar.gz
  sha256: 86ac6cee19f6c945e8dedf78c6ee74f1112bd14da5a658d8c9d4103aed5756a2

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - elftools
    - elftools.common
    - elftools.construct
    - elftools.construct.lib
    - elftools.dwarf
    - elftools.elf

about:
  home: https://github.com/eliben/pyelftools
  license: Public Domain
  license_file: LICENSE
  summary: Library for analyzing ELF files and DWARF debugging information

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
