{% set version = "0.23" %}

package:
  name: pyelftools
  version: {{ version }}

source:
  fn: pyelftools-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/pyelftools/pyelftools-{{ version }}.tar.gz
  md5: aa7cefa8bd2f63d7b017440c9084f310

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - elftools
    - elftools.common
    - elftools.construct
    - elftools.construct.lib
    - elftools.dwarf
    - elftools.elf

about:
  home: https://github.com/eliben/pyelftools
  license: Public domain
  summary: 'Library for analyzing ELF files and DWARF debugging information'

extra:
  recipe-maintainers:
    - msarahan
