{% set version = "0.27" %}

package:
  name: pyelftools
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyelftools/pyelftools-{{ version }}.tar.gz
  sha256: cde854e662774c5457d688ca41615f6594187ba7067af101232df889a6b7a66b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - elftools
    - elftools.common
    - elftools.construct
    - elftools.construct.lib
    - elftools.dwarf
    - elftools.elf

about:
  home: https://github.com/eliben/pyelftools
  license: Public Domain
  license_file: LICENSE
  summary: Library for analyzing ELF files and DWARF debugging information

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
