{% set version = "0.25" %}

package:
  name: pyelftools
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyelftools/pyelftools-{{ version }}.tar.gz
  sha256: 89c6da6f56280c37a5ff33468591ba9a124e17d71fe42de971818cbff46c1b24

build:
  number: 1000
  skip: True  # [not linux]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - elftools
    - elftools.common
    - elftools.construct
    - elftools.construct.lib
    - elftools.dwarf
    - elftools.elf

about:
  home: https://github.com/eliben/pyelftools
  license: Public Domain
  license_file: LICENSE
  summary: Library for analyzing ELF files and DWARF debugging information

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
