travis:
  secure:
    BINSTAR_TOKEN: ojiTcQFfu4WvoE+B1U7LDcaPYTRXO2HLOm3RuAjl0nZGSKzhpVZum3v9uzCKsjKy9Tu+DLtzujYW+7ZRvG9MNQkIvrLfkMF4/9oehv0owtDm6HayTeflAYGADiQI2DUiO9h+eP09iB6hA/DypzGZaXBFLSVbLnI1p7d1R7uUGyGM4mOC4P/Y/O93jHn8B3NG0gF8bLJHaqfb1gC4yCJyAAXLKWfg+4Q/O5UMb7AnVYeBnAMQ12KRSxYnPuQW3H8lercaCebslaif/q5dDDSnoxXboJjz4fIxfZnn5M7OqGWQXq9YDM5ZH3/js5Co3vrar+kPfde5U1G7+MFMfYS7M2OLVdSmsaf1emJMdJFdyZO6UFeN49g/hnquWikPstyifFYG1jKJtrmo3gD2p1DBbzUQwPEr9mJTRi1ugLlt21yNfzijmjtBWR/Td2Hgu9OlxyYMeOJ9GF5SAVZJTF+zSyceg3O9xPzsNgbpUplcQf6d3kfpL79mzPgmiNgkrxiQsB5wTRlFPknTzQEJVrXD/MpvXbOGiYh0kLZt+bUlok1VPvgD39dzcDYFe4vAhl4qvPgil41SFiKM0FCzlp6L9ChpKEYSluU4LUmVwD2dqvKepShmlNhlPk/Yk7VkOvNMw89iYF1erbRDblsjsOe/uu0q7lJiFWjcHc81lu7rr3U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
