appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: is88udtrbZMWE/U2x3tWPMM/48pZIiXxtTI/AsqoopeVckeLhwlSMND6+HD24a+bVIa7gxolTPYGhh869RfV04/OM9jZzCChEbk9UfCvlby/Ozz+ukuf/+HfH6+OER8HqCrR0aiMqKF2XJreIyVYaxKp0RGaWOKI1dh25M0e1ZQ7ZbYMqJx4Y9Qx8KEyur/j2ftiKHDnBI1RKJqIwO+tG3CW8TyqdyZWwbNyXgBQuRzq7ZdCaKNow6Tjb7dL/C9a09kZgXDqG8pP9mIossPv9zLVsJ2zc4gLUVevXoWt9gxMW+Q1dwfyCOlLbiiDJKDlBhuVeYQobEitg0Wza8j22rBlWQ0dIFCouW8o9nDguaSf1rAlqA6R/8nmmkzCyk970MAAqLrx4WO/Sf0RW9ohNo+sk10imTIBa8gWwsIyiisjzNUcEE69hCCwkCvIKFyFUPdCxtWKte48UhyD/o7oeZCyITVlun7bPho3I7iKwPYh0RZjmsS2Q02aIQSLmPxdqQ/6iSyoJuGLOtRpQ/NrhurokL3mOT1kwJGk/msqPCOdMj/aM/li+bjzee45L6Y/DjMxEaEGZ8cw2GFviDXfX+95DueJ5Rt8+RnRSPMtG3avg3jKuGZxJXCvoksjFqbPiLLH/7RTyOVX/22agpgcZ5Q4TKxOvCmYYJQ7Mp4bH8k=}
conda_forge_output_validation: true
