travis:
  secure:
    BINSTAR_TOKEN: TW3tPAlQQEPDez7RnzkcBNFgdD+yMj5RIzN01wxqMdeO7aHvUJLXxjUArzKBCZAm7DqdVqPEB51zlEbIc5jUGY88N0KzOGy2mmgsmhahqMRcAkFu5wprVZYSTmFfjOVAr+hiwZhvudzC4Rl60VQ+scWX7Z5AgclHg2RHDZx0NSpHhGrApQ8vaIImx0sbFL4/75EgGcoITQG/Vrs4ZUsimdMHfn6CYofVlU4g2qdkj4GRlXHnOjN5gXNHzpfl3yoJVnc7Amo0u5Leps8pv9SRnpuJy/0hhGwe1aPtyV1Q0Dfincmy++eUibyP0OF+Rq5Xie6kBmuKqhv+3YVNWjTLj+3yK83HTcRkf2UlIrJ04RX+jtObUnbm6mD5hFuJ+xgqCn1vM6GUoHdWpcZXU9Mu5leqprTZYygaj8i45W5KxihJC+97/TIS/aPQpW7c3wab46IaWtpeOdYBvkTjokK69BaSpcVFE/w8y/71VdtrcDSdcDNtVDYBlY8Y87Kk81iWleIiPL6IZh0UhAMosMEyNoJBG35OVdk+fDn8KK6D3EPbzh37QdWTSzw2/DBGYYR0HhYBFJaC29E7qvr/FMqhiW1I2/L/WQMJea/AsPtpWAcUr1VlICEy6o82C7AGCkanROdc45B0GRNg1CGxZ8IeofaGQYQCa/z65JCWx4+DedA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
